Bol/Bol/Controllers/AdminController.cs
namespace Bol.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Web;
    using System.Web.Mvc;

    public class AdminController : Controller
    {
        /// <summary>
        /// Shows the admin panel.
        /// </summary>
        /// <returns>Returns the admin view.</returns>
        public ActionResult Index()
        {
            return View();
        }
    }
}

Bol/Bol/Controllers/ProductController.cs
using System.Web.Mvc;
using Bol.Models;
using Bol.Repository;
using Bol.Repository.ShoppingCart;

namespace Bol.Controllers
{
    /// <summary>
    /// The product controller.
    /// </summary>
    public class ProductController : Controller
    {
        private ProductRepository productRepo = new ProductRepository();
        private AccountRepository accountRepo = new AccountRepository();
        private ShoppingCartRepository cartRepo = new ShoppingCartRepository();

        /// <summary>
        /// The product index view.
        /// </summary>
        /// <returns>View with all products.</returns>
        public ActionResult Index()
        {
            if (!loggedInAsAdmin())
            {
                return RedirectToAction("Index", "Home");
            }

            return View(productRepo.GetAll());
        }

        /// <summary>
        /// View product view.
        /// </summary>
        /// <param name="id">The id of the product to view.</param>
        /// <returns>View the product view.</returns>
        public ActionResult View(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("Index", "Home");
            }

            Product product = productRepo.GetById((int)id);
            return View(product);
        }

        /// <summary>
        /// The account currently logged in.
        /// </summary>
        /// <returns>Account currently logged in.</returns>
        private Account getLoggedIn()
        {
            Account account = null;
            if (Session["email"] != null)
            {
                account = accountRepo.getAccount(Session["email"].ToString());
            }

            return account;
        }

        /// <summary>
        /// Checks whether the account currently logged in is an admin.
        /// </summary>
        /// <returns>Whether an admin is logged in.</returns>
        private bool loggedInAsAdmin()
        {
            if (Session["email"] == null || !accountRepo.isAdmin(Session["email"].ToString()))
            {
                return false;
            }

            return true;
        }

        /// <summary>
        /// Checks whether someone is currently logged in.
        /// </summary>
        /// <returns>Whether someone is logged in.</returns>
        private bool loggedIn()
        {
            if (Session["email"] == null)
            {
                return false;
            }

            return true;
        }

        /// <summary>
        /// Gets the edit product view.
        /// </summary>
        /// <param name="id">The id of the product to edit.</param>
        /// <returns>Returns edit product view.</returns>
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return HttpNotFound();
            }

            if (!loggedInAsAdmin())
            {
                return RedirectToAction("Index", "Home");
            }

            Product product = productRepo.GetById((int)id);
            return View(product);
        }

        /// <summary>
        /// Edit product.
        /// </summary>
        /// <param name="product">The product to edit.</param>
        /// <returns>Return edit product view.</returns>
        [HttpPost]
        public ActionResult Edit(Product product)
        {
            if (!ModelState.IsValid)
            {
                return View(product);
            }

            if (!loggedInAsAdmin())
            {
                return RedirectToAction("Index", "Home");
            }

            if (!productRepo.UpdateProduct(product))
            {
                ViewData["error"] = "Invalid field!";
                return View(product);
            }

            return RedirectToAction("Index");
        }

        /// <summary>
        /// Add product view.
        /// </summary>
        /// <returns>The add product view.</returns>
        [HttpGet]
        public ActionResult Add()
        {
            if (!loggedInAsAdmin())
            {
                return RedirectToAction("Index", "Home");
            }

            return View();
        }

        [HttpPost]
        public ActionResult Add(Product product)
        {
            if (!ModelState.IsValid)
            {
                return View(product);
            }

            if (!loggedInAsAdmin())
            {
                return RedirectToAction("Index", "Home");
            }

            if (!productRepo.AddProduct(product))
            {
                ViewData["error"] = "Invalid field!";
                return View(product);
            }

            return RedirectToAction("Index");
        }
    }
}

Bol/Bol/Views/Shared/LoginPartial.cshtml
<ul class="nav navbar-nav navbar-right">
    @if (Session["Email"] == null)
    {
        <li>@Html.ActionLink("Register", "Register", "Account")</li>
        <li>@Html.ActionLink("Log in", "Login", "Account")</li>
    }
    else
    {
        <li>@Html.ActionLink("Logged in as " + Session["Email"], "Profile", "Account")</li>
        <li>@Html.ActionLink("Log out", "LogOut", "Account")</li>
    }
</ul>

Bol/Bol/Views/Shared/_Layout.cshtml
@using Bol.Repository
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - ASP.NET Application By Simin Jacobs</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Bol", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <!--<li>@Html.ActionLink("Home", "Index", "Home")</li>-->
                    <!--<li>@Html.ActionLink("About", "About", "Home")</li>-->
                    <!--<li>@Html.ActionLink("Accounts", "Index", "Account")</li>-->
                    <!--<li>@Html.ActionLink("Products", "Index", "Product")</li>-->
                    <li>@Html.ActionLink("Wishlist", "Index", "Wishlist")</li>
                    <li>@Html.ActionLink("Shopping cart", "Index", "ShoppingCart")</li>
                    @if (Session["email"] != null && new AccountRepository().getAccount(Session["email"].ToString()).isAdmin)
                    {
                        <li>@Html.ActionLink("Admin panel", "Index", "Admin")</li>
                    }
                </ul>
                @Html.Partial("LoginPartial")
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav"></ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>