Bol/Bol/Models/Product.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Bol.Models
{
    public class Product
    {
        /// <summary>
        /// Gets or sets the id.
        /// </summary>
        /// <value>The id of the product.</value>
        public int Id { get; set; }

        /// <summary>
        /// Gets or sets the category id.
        /// </summary>
        /// <value>The category id of the product.</value>
        public int CategoryId { get; set; }

        /// <summary>
        /// Gets or sets the name.
        /// </summary>
        /// <value>The name of the product.</value>
        public string Name { get; set; }

        /// <summary>
        /// Gets or sets the price.
        /// </summary>
        /// <value>The price of the product.</value>
        public decimal Price { get; set; }

        /// <summary>
        /// Gets or sets the brand.
        /// </summary>
        /// <value>The brand of the product.</value>
        public string Brand { get; set; }

        /// <summary>
        /// Gets or sets the type.
        /// </summary>
        /// <value>The type of the product.</value>
        public string Type { get; set; }

        /// <summary>
        /// Gets or sets a value indicating whether the product is used.
        /// </summary>
        /// <value>The product is used.</value>
        public bool Used { get; set; }

        /// <summary>
        /// Gets or sets the properties.
        /// </summary>
        /// <value>The properties of the product.</value>
        public string Properties { get; set; }

        /// <summary>
        /// Gets or sets the description.
        /// </summary>
        /// <value>The description of the product.</value>
        public string Description { get; set; }

        public Product()
        {
        }

        public Product(int id, int categoryId, string name, decimal price, string brand, string type, bool used, string properties, string description)
        {
            Id = id;
            CategoryId = categoryId;
            Name = name;
            Price = price;
            Brand = brand;
            Type = type;
            Used = used;
            Properties = properties;
            Description = description;
        }

        /// <summary>
        /// The description of the product.
        /// </summary>
        /// <returns>The description of product.</returns>
        public override string ToString()
        {
            return Id + ". " + Name + " " + Price + " eur";
        }
    }
}

Bol/Bol/Controllers/ProductController.cs
using System.Web.Mvc;
using Bol.Models;
using Bol.Repository;
using Bol.Repository.ShoppingCart;

namespace Bol.Controllers
{
    /// <summary>
    /// The product controller.
    /// </summary>
    public class ProductController : Controller
    {
        private ProductRepository productRepo = new ProductRepository();
        private AccountRepository accountRepo = new AccountRepository();
        private ShoppingCartRepository cartRepo = new ShoppingCartRepository();

        /// <summary>
        /// The product index view.
        /// </summary>
        /// <returns>View with all products.</returns>
        public ActionResult Index()
        {
            if (!loggedInAsAdmin())
            {
                return RedirectToAction("Index", "Home");
            }

            return View(productRepo.GetAll());
        }

        /// <summary>
        /// View product view.
        /// </summary>
        /// <param name="id">The id of the product to view.</param>
        /// <returns>View the product view.</returns>
        public ActionResult View(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("Index", "Home");
            }

            Product product = productRepo.GetById((int)id);
            return View(product);
        }

        /// <summary>
        /// The account currently logged in.
        /// </summary>
        /// <returns>Account currently logged in.</returns>
        private Account getLoggedIn()
        {
            Account account = null;
            if (Session["email"] != null)
            {
                account = accountRepo.getAccount(Session["email"].ToString());
            }

            return account;
        }

        /// <summary>
        /// Checks whether the account currently logged in is an admin.
        /// </summary>
        /// <returns>Whether an admin is logged in.</returns>
        private bool loggedInAsAdmin()
        {
            if (Session["email"] == null || !accountRepo.isAdmin(Session["email"].ToString()))
            {
                return false;
            }

            return true;
        }

        /// <summary>
        /// Checks whether someone is currently logged in.
        /// </summary>
        /// <returns>Whether someone is logged in.</returns>
        private bool loggedIn()
        {
            if (Session["email"] == null)
            {
                return false;
            }

            return true;
        }

        /// <summary>
        /// Gets the edit product view.
        /// </summary>
        /// <param name="id">The id of the product to edit.</param>
        /// <returns>Returns edit product view.</returns>
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return HttpNotFound();
            }

            if (!loggedInAsAdmin())
            {
                return RedirectToAction("Index", "Home");
            }

            Product product = productRepo.GetById((int)id);
            return View(product);
        }

        /// <summary>
        /// Edit product.
        /// </summary>
        /// <param name="product">The product to edit.</param>
        /// <returns>Return edit product view.</returns>
        [HttpPost]
        public ActionResult Edit(Product product)
        {
            if (!ModelState.IsValid)
            {
                return View(product);
            }

            if (!loggedInAsAdmin())
            {
                return RedirectToAction("Index", "Home");
            }

            if (!productRepo.UpdateProduct(product))
            {
                ViewData["error"] = "Invalid field!";
                return View(product);
            }

            return RedirectToAction("Index");
        }

        /// <summary>
        /// Add product view.
        /// </summary>
        /// <returns>The add product view.</returns>
        [HttpGet]
        public ActionResult Add()
        {
            if (!loggedInAsAdmin())
            {
                return RedirectToAction("Index", "Home");
            }

            return View();
        }

        [HttpPost]
        public ActionResult Add(Product product)
        {
            if (!ModelState.IsValid)
            {
                return View(product);
            }

            if (!loggedInAsAdmin())
            {
                return RedirectToAction("Index", "Home");
            }

            if (!productRepo.AddProduct(product))
            {
                ViewData["error"] = "Invalid field!";
                return View(product);
            }

            return RedirectToAction("Index");
        }
    }
}

Bol/Bol/Controllers/WishlistController.cs
using System.Web.Mvc;
using Bol.Models;
using Bol.Repository;

namespace Bol.Controllers
{
    public class WishlistController : Controller
    {
        private WishlistRepository wishlistRepo = new WishlistRepository();
        private AccountRepository accountRepo = new AccountRepository();
        private ProductRepository productRepo = new ProductRepository();

        /// <summary>
        /// Wish list view.
        /// </summary>
        /// <returns>View with all wish lists.</returns>
        public ActionResult Index()
        {
            if (!loggedIn())
            {
                return RedirectToAction("Login", "Account");
            }

            return View(wishlistRepo.GetProducts(loggedInAccount()));
        }

        /// <summary>
        /// Add product to wish list.
        /// </summary>
        /// <param name="id">The id of the product to add.</param>
        /// <returns>Add product view.</returns>
        public ActionResult AddProduct(int? id)
        {
            if (!loggedIn())
            {
                return RedirectToAction("Login", "Account");
            }

            if (id == null)
            {
                return RedirectToAction("Index", "Home");
            }

            Product product = productRepo.GetById((int)id);
            wishlistRepo.AddProduct(loggedInAccount(), product);
            return RedirectToAction("Index");
        }

        /// <summary>
        /// Delete product from wish list.
        /// </summary>
        /// <param name="id">The id of the product to delete.</param>
        /// <returns>Delete product view.</returns>
        public ActionResult DeleteProduct(int? id)
        {
            if (!loggedIn())
            {
                return RedirectToAction("Login", "Account");
            }

            if (id == null)
            {
                return RedirectToAction("Index", "Home");
            }
            
            Product product = productRepo.GetById((int)id);
            wishlistRepo.DeleteProduct(loggedInAccount(), product);
            return RedirectToAction("Index");
        }

        /// <summary>
        /// Gets the logged in account.
        /// </summary>
        /// <returns>Logged in account.</returns>
        private Account loggedInAccount()
        {
            Account account = null;
            if (loggedIn())
            {
                account = accountRepo.getAccount(Session["email"].ToString());
            }

            return account;
        }

        private bool loggedIn()
        {
            return Session["email"] != null;
        }
    }
}

Bol/Bol/Views/Product/Add.cshtml
@using Bol.Models
@model Product

@{
    ViewBag.Title = "Add";
}

<h2>Add product</h2>

@using (Html.BeginForm("Add", "Product", FormMethod.Post, new { @class = "form-horizontal" }))
{
    <form class="form-horizontal">
        <div class="form-group">
            @Html.LabelFor(m => m.Name, new { placeholder = "Name", @class = "control-label col-md-2" })
            <div class="col-sm-10">
                @Html.TextBoxFor(m => m.Name, new { placeholder = "Name" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(m => m.Price, new { placeholder = "Price", @class = "control-label col-md-2" })
            <div class="col-sm-10">
                @Html.TextBoxFor(m => m.Price, new { placeholder = "Price" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(m => m.Brand, new { placeholder = "Brand", @class = "control-label col-md-2" })
            <div class="col-sm-10">
                @Html.TextBoxFor(m => m.Brand, new { placeholder = "Brand" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(m => m.CategoryId, new { placeholder = "CategoryId", @class = "control-label col-md-2" })
            <div class="col-sm-10">
                @Html.TextBoxFor(m => m.CategoryId, new { placeholder = "CategoryId" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(m => m.Description, new { placeholder = "Description", @class = "control-label col-md-2" })
            <div class="col-sm-10">
                @Html.TextBoxFor(m => m.Description, new { placeholder = "Description" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(m => m.Properties, new { placeholder = "Properties", @class = "control-label col-md-2" })
            <div class="col-sm-10">
                @Html.TextBoxFor(m => m.Properties, new { placeholder = "Properties" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(m => m.Type, new { placeholder = "Type", @class = "control-label col-md-2" })
            <div class="col-sm-10">
                @Html.TextBoxFor(m => m.Type, new { placeholder = "Type" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(m => m.Used, new { placeholder = "Used", @class = "control-label col-md-2" })
            <div class="col-sm-10">
                @Html.CheckBoxFor(m => m.Used)
            </div>
        </div>

        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
                <button type="submit" class="btn btn-default">Add product</button>
            </div>
        </div>
    </form>
}

@if (ViewData["Error"] != null)
{
    <div class="red">
        <p>@ViewData["Error"]</p>
    </div>
}

Bol/Bol/Views/Product/Edit.cshtml
@using Bol.Models
@model Product

@{
    ViewBag.Title = "Edit";
}

<h2>Edit product</h2>

@if (Model != null)
{
    using (Html.BeginForm("Edit", "Product", FormMethod.Post, new { @class = "form-horizontal" }))
    {
        <form class="form-horizontal">
            <div class="form-group">
                @Html.LabelFor(m => m.Name, new { placeholder = "Name", @class = "control-label col-md-2" })
                <div class="col-sm-10">
                    @Html.TextBoxFor(m => m.Name, new { value = @Model.Name, placeholder = "Name" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(m => m.Price, new { placeholder = "Price", @class = "control-label col-md-2" })
                <div class="col-sm-10">
                    @Html.TextBoxFor(m => m.Price, new { value = @Model.Price, placeholder = "Price" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(m => m.Brand, new { placeholder = "Brand", @class = "control-label col-md-2" })
                <div class="col-sm-10">
                    @Html.TextBoxFor(m => m.Brand, new { value = @Model.Brand, placeholder = "Brand" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(m => m.CategoryId, new { placeholder = "CategoryId", @class = "control-label col-md-2" })
                <div class="col-sm-10">
                    @Html.TextBoxFor(m => m.CategoryId, new { value = @Model.CategoryId, placeholder = "CategoryId" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(m => m.Description, new { placeholder = "Description", @class = "control-label col-md-2" })
                <div class="col-sm-10">
                    @Html.TextBoxFor(m => m.Description, new { value = @Model.Description, placeholder = "Description" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(m => m.Properties, new { placeholder = "Properties", @class = "control-label col-md-2" })
                <div class="col-sm-10">
                    @Html.TextBoxFor(m => m.Properties, new { value = @Model.Properties, placeholder = "Properties" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(m => m.Type, new { placeholder = "Type", @class = "control-label col-md-2" })
                <div class="col-sm-10">
                    @Html.TextBoxFor(m => m.Type, new { value = @Model.Type, placeholder = "Type" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(m => m.Used, new { value = @Model.Used, placeholder = "Used", @class = "control-label col-md-2" })
                <div class="col-sm-10">
                    @Html.CheckBoxFor(m => m.Used)
                </div>
            </div>

            <div class="form-group">
                <div class="col-sm-offset-2 col-sm-10">
                    <button type="submit" class="btn btn-default">Update product</button>
                </div>
            </div>
        </form>
    }
}

@if (ViewData["Error"] != null)
{
    <div class="red">
        <p>@ViewData["Error"]</p>
    </div>
}

Bol/Bol/Views/Product/Index.cshtml
@using Bol.Models
@model List<Product>

@{
    ViewBag.Title = "Index";
}

<h2>Products</h2>
<ul>
    @foreach (Product product in Model)
    {
        <li>
            <a href="@Url.Action("Edit", "Product", new { id = @product.Id })">@product</a>
        </li>
    }
</ul>

<a href="~/Product/Add">Voeg een product toe</a>

Bol/Bol/Views/Product/View.cshtml
@using Bol.Models
@model Product
@{
    ViewBag.Title = "View";
}

<h2>@Model.Name</h2>

Name: @Model.Name <br />
Price: @Model.Price <br />
CategoryId: @Model.CategoryId <br />
Brand: @Model.Brand <br />
Description: @Model.Description <br />

<div class="form-group">
    <a href="@Url.Action("AddProduct", "ShoppingCart", new { id = @Model.Id })" class="btn btn-default">Add to cart</a>
    <a href="@Url.Action("AddProduct", "Wishlist", new { id = @Model.Id })" class="btn btn-default">Add to wishlist</a>
</div>