Bol/Bol/Models/Category.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Web;

namespace Bol.Models
{
    public class Category
    {
        /// <summary>
        /// Gets or sets the Id.
        /// </summary>
        /// <value>The id of the category.</value>
        public int Id { get; set; }

        /// <summary>
        /// Gets or sets the Name.
        /// </summary>
        /// <value>The name of the category.</value>
        public string Name { get; set; }

        /// <summary>
        /// Gets or sets the list of products.
        /// </summary>
        /// <value>The products of the category.</value>
        public List<Product> Products { get; set; }

        /// <summary>
        /// Gets or sets the parent category id.
        /// </summary>
        /// <value>The parent category id of the category.</value>
        [DisplayName("Parent category id")]
        public int ParentCategoryId { get; set; }

        /// <summary>
        /// Gets or sets the child categories.
        /// </summary>
        /// <value>The child categories of the category.</value>
        public List<Category> ChildCategories { get; set; }

        public Category()
        {
        }

        public Category(int id, string name)
        {
            Id = id;
            Name = name;
        }

        public Category(int id, string name, int parentCategoryId, List<Category> childCategories)
        {
            Id = id;
            Name = name;
            ParentCategoryId = parentCategoryId;
            ChildCategories = childCategories;
        }

        /// <summary>
        /// Description of the category.
        /// </summary>
        /// <returns>The description of the category.</returns>
        public override string ToString()
        {
            return Id + ". " + Name;
        }
    }
}

Bol/Bol/Controllers/CategoryController.cs
namespace Bol.Controllers
{
    using System.Web.Mvc;
    using Bol.Repository;
    using Models;

    public class CategoryController : Controller
    {
        private CategoryRepository categoryRepo = new CategoryRepository();
        private AccountRepository accountRepo = new AccountRepository();

        /// <summary>
        /// The view with all categories.
        /// </summary>
        /// <returns>Returns the view with categories.</returns>
        public ActionResult Index()
        {
            return View(categoryRepo.GetAll());
        }

        /// <summary>
        /// The view of a single category.
        /// </summary>
        /// <param name="id">The id of the category.</param>
        /// <returns>The category view.</returns>
        public ActionResult View(int? id)
        {
            if (id == null)
            {
                return HttpNotFound();
            }

            Category category = categoryRepo.GetCategory((int)id);
            return View(category);
        }

        /// <summary>
        /// Checks whether an admin is currently logged in.
        /// </summary>
        /// <returns>Returns whether an admin is logged in.</returns>
        private bool loggedInAsAdmin()
        {
            if (Session["email"] == null || !accountRepo.isAdmin(Session["email"].ToString()))
            {
                return false;
            }

            return true;
        }

        /// <summary>
        /// Edit a category.
        /// </summary>
        /// <param name="id">The id of the category to edit.</param>
        /// <returns>Returns an edit view.</returns>
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return HttpNotFound();
            }

            if (!loggedInAsAdmin())
            {
                return RedirectToAction("Index", "Home");
            }

            Category category = categoryRepo.GetCategory((int)id);
            return View(category);
        }

        /// <summary>
        /// Edit category view.
        /// </summary>
        /// <param name="category">Category to edit.</param>
        /// <returns>The edit category view.</returns>
        [HttpPost]
        public ActionResult Edit(Category category)
        {
            if (!ModelState.IsValid)
            {
                return View(category);
            }

            if (!loggedInAsAdmin())
            {
                return RedirectToAction("Index", "Home");
            }

            if (!categoryRepo.UpdateCategory(category))
            {
                ViewData["error"] = "Invalid field!";
                return View(category);
            }

            return RedirectToAction("Index");
        }

        /// <summary>
        /// Add category view.
        /// </summary>
        /// <returns>Add the category view.</returns>
        [HttpGet]
        public ActionResult Add()
        {
            if (!loggedInAsAdmin())
            {
                return RedirectToAction("Index", "Home");
            }

            return View();
        }

        /// <summary>
        /// Add category view.
        /// </summary>
        /// <param name="category">The category to add.</param>
        /// <returns>View with category.</returns>
        [HttpPost]
        public ActionResult Add(Category category)
        {
            if (!loggedInAsAdmin())
            {
                return RedirectToAction("Index", "Home");
            }

            if (!categoryRepo.AddCategory(category))
            {
                ViewData["error"] = "Invalid field!";
                return View(category);
            }

            return RedirectToAction("Index");
        }
    }
}

Bol/Bol/Controllers/ProductController.cs
using System.Web.Mvc;
using Bol.Models;
using Bol.Repository;
using Bol.Repository.ShoppingCart;

namespace Bol.Controllers
{
    /// <summary>
    /// The product controller.
    /// </summary>
    public class ProductController : Controller
    {
        private ProductRepository productRepo = new ProductRepository();
        private AccountRepository accountRepo = new AccountRepository();
        private ShoppingCartRepository cartRepo = new ShoppingCartRepository();

        /// <summary>
        /// The product index view.
        /// </summary>
        /// <returns>View with all products.</returns>
        public ActionResult Index()
        {
            if (!loggedInAsAdmin())
            {
                return RedirectToAction("Index", "Home");
            }

            return View(productRepo.GetAll());
        }

        /// <summary>
        /// View product view.
        /// </summary>
        /// <param name="id">The id of the product to view.</param>
        /// <returns>View the product view.</returns>
        public ActionResult View(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("Index", "Home");
            }

            Product product = productRepo.GetById((int)id);
            return View(product);
        }

        /// <summary>
        /// The account currently logged in.
        /// </summary>
        /// <returns>Account currently logged in.</returns>
        private Account getLoggedIn()
        {
            Account account = null;
            if (Session["email"] != null)
            {
                account = accountRepo.getAccount(Session["email"].ToString());
            }

            return account;
        }

        /// <summary>
        /// Checks whether the account currently logged in is an admin.
        /// </summary>
        /// <returns>Whether an admin is logged in.</returns>
        private bool loggedInAsAdmin()
        {
            if (Session["email"] == null || !accountRepo.isAdmin(Session["email"].ToString()))
            {
                return false;
            }

            return true;
        }

        /// <summary>
        /// Checks whether someone is currently logged in.
        /// </summary>
        /// <returns>Whether someone is logged in.</returns>
        private bool loggedIn()
        {
            if (Session["email"] == null)
            {
                return false;
            }

            return true;
        }

        /// <summary>
        /// Gets the edit product view.
        /// </summary>
        /// <param name="id">The id of the product to edit.</param>
        /// <returns>Returns edit product view.</returns>
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return HttpNotFound();
            }

            if (!loggedInAsAdmin())
            {
                return RedirectToAction("Index", "Home");
            }

            Product product = productRepo.GetById((int)id);
            return View(product);
        }

        /// <summary>
        /// Edit product.
        /// </summary>
        /// <param name="product">The product to edit.</param>
        /// <returns>Return edit product view.</returns>
        [HttpPost]
        public ActionResult Edit(Product product)
        {
            if (!ModelState.IsValid)
            {
                return View(product);
            }

            if (!loggedInAsAdmin())
            {
                return RedirectToAction("Index", "Home");
            }

            if (!productRepo.UpdateProduct(product))
            {
                ViewData["error"] = "Invalid field!";
                return View(product);
            }

            return RedirectToAction("Index");
        }

        /// <summary>
        /// Add product view.
        /// </summary>
        /// <returns>The add product view.</returns>
        [HttpGet]
        public ActionResult Add()
        {
            if (!loggedInAsAdmin())
            {
                return RedirectToAction("Index", "Home");
            }

            return View();
        }

        [HttpPost]
        public ActionResult Add(Product product)
        {
            if (!ModelState.IsValid)
            {
                return View(product);
            }

            if (!loggedInAsAdmin())
            {
                return RedirectToAction("Index", "Home");
            }

            if (!productRepo.AddProduct(product))
            {
                ViewData["error"] = "Invalid field!";
                return View(product);
            }

            return RedirectToAction("Index");
        }
    }
}

Bol/Bol/Views/Category/Add.cshtml
@using Bol.Models
@model Category
@{
    ViewBag.Title = "Add";
}

<h2>Add category</h2>

@using (Html.BeginForm("Add", "Category", FormMethod.Post, new { @class = "form-horizontal" }))
{
    <form class="form-horizontal">
        <div class="form-group">
            @Html.LabelFor(m => m.Name, new { @class = "control-label col-md-2" })
            <div class="col-sm-10">
                @Html.TextBoxFor(m => m.Name, new { placeholder = "Name" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(m => m.ParentCategoryId, new { @class = "control-label col-md-2" })
            <div class="col-sm-10">
                @Html.TextBoxFor(m => m.ParentCategoryId, new { placeholder = "Upper category id" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
                <button type="submit" class="btn btn-default">Add category</button>
            </div>
        </div>
    </form>
}

@if (ViewData["Error"] != null)
{
    <div class="red">
        <p>@ViewData["Error"]</p>
    </div>
}

Bol/Bol/Views/Category/Index.cshtml
@using Bol.Models
@using Bol.Repository
@model List<Category>

@{
    ViewBag.Title = "Index";
}

<h2>Choose a category</h2>

<ul>
    @foreach (Category category in Model)
    {
        if (category.ParentCategoryId != 0)
        {
            continue;
        }
        <li>
            <h3>
                @if (Session["email"] != null && new AccountRepository().isAdmin(Session["email"].ToString()))
                {
                    <text>(id @category.Id)</text>
                }
                <a href="@Url.Action("View", "Category", new { id = @category.Id })">@category.Name</a>
            </h3>
            <ul>
                @foreach (Product product in category.Products)
                {
                    <li>
                        @if (Session["email"] != null && new AccountRepository().isAdmin(Session["email"].ToString()))
                    {
                            <text>(id @product.Id)</text>
                        }
                        <a href="@Url.Action("View", "Product", new { id = @product.Id })">@product.Name (&#8364 @product.Price)</a>
                    </li>
                }
            </ul>

            <ul>
                @foreach (Category childCategory in category.ChildCategories)
                {
                    if (childCategory.Products.Count == 0 && (Session["email"] == null || !new AccountRepository().isAdmin(Session["email"].ToString())))
                    {
                        continue;
                    }
                    <li>
                        <h4>
                            @if (Session["email"] != null && new AccountRepository().isAdmin(Session["email"].ToString()))
                    {
                                <text>(id @childCategory.Id)</text>
                            }
                            <a href="@Url.Action("View", "Category", new { id = @childCategory.Id })">@childCategory.Name</a>
                        </h4>
                        <ul>
                            @foreach (Product product in childCategory.Products)
                    {
                                <li>
                                    @if (Session["email"] != null && new AccountRepository().isAdmin(Session["email"].ToString()))
                                    {
                                        <text>(id @product.Id)</text>
                                    }
                                    <a href="@Url.Action("View", "Product", new { id = @product.Id })">@product.Name (&#8364 @product.Price)</a>
                                </li>
                            }
                        </ul>
                    </li>
                }

            </ul>
        </li>
    }
</ul>

Bol/Bol/Views/Category/View.cshtml
@using Bol.Models
@using Bol.Repository
@model Category
@{
    ViewBag.Title = "View";
}

<h2>@Model.Name</h2>
<ul>
    @foreach (Product product in Model.Products)
    {
        <li>
            @if (Session["email"] != null && new AccountRepository().isAdmin(Session["email"].ToString()))
            {
                <text>(id @product.Id)</text>
            }
            <a href="@Url.Action("View", "Product", new { id = @product.Id })">@product.Name (&#8364 @product.Price)</a>
        </li>
    }
</ul>